# Generated by Django 4.2.7 on 2024-01-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_cart_remove_cartitem_product_and_more'),
        ('core', '0003_alter_customer_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
