# Generated by Django 4.2.7 on 2024-01-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('unit', 'Unit'), ('weight', 'Weight')], max_length=10)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
